apiVersion: v1
kind: Service
metadata:
  name: modernbank-transfer
  namespace: modernbank
spec:
  selector:
    app: modernbank-transfer
    project: modernbank
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
