apiVersion: v1
kind: Service
metadata:
  name: modernbank-account
  namespace: modernbank
spec:
  selector:
    app: modernbank-account
    project: modernbank
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
