apiVersion: v1
kind: Service
metadata:
  name: modernbank-cqrs
  namespace: modernbank
spec:
  selector:
    app: modernbank-cqrs
    project: modernbank
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
