apiVersion: v1
kind: Service
metadata:
  name: modernbank
  namespace: modernbank
spec:
  selector:
    app: modernbank
    project: modernbank
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: ClusterIP
