apiVersion: apps/v1
kind: Deployment
metadata:
  name: modernbank-product
  namespace: modernbank
  labels:
    app: modernbank-product
    project: modernbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modernbank-product
      project: modernbank
  template:
    metadata:
      labels:
        app: modernbank-product
        project: modernbank
    spec:
      serviceAccountName: modernbank-product-sa
      containers:
      - name: modernbank-product
        image: 216989108269.dkr.ecr.ap-northeast-2.amazonaws.com/modernbank-product:latest  # ECR 이미지 주소
        ports:
        - containerPort: 8086
        env:
        - name: ACCOUNT_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: account-service
        - name: B2BT_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: b2bt-service
        - name: CUSTOMER_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: customer-service
        - name: CQRS_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: cqrs-service
        - name: TRANSFER_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: transfer-service
        - name: KAFKA_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: kafka-service
        - name: POSTGRES_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: postgres-service
        - name: POSTGRES_SERVICE_USER
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: postgres-user
        - name: POSTGRES_SERVICE_PASS
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: postgres-pass
        - name: DDB_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: ddb-service
        - name: DDB_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: ddb-access-key
        - name: DDB_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: modernbank-services-cm
              key: ddb-secret-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"